### ISSUE TITLE
"Request for image failed"

### ISSUE THREAD

**Issue by patrick-men** [Inlyne-Project/inlyne#319] opened 2024-04-15 11:45 UTC
I tried to preview a markdown file with an image in it. When opening it with `inlyne nodes.md --theme dark` I get the following error in the terminal:

2024-04-15T11:36:17.612004Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612026Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612033Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612036Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612039Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612042Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612045Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612049Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612052Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612055Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612066Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612072Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612075Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612078Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612081Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612167Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612195Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.612209Z  INFO inlyne::interpreter: Missing implementation for start tag: click
2024-04-15T11:36:17.618573Z  WARN inlyne::image: Request for image from ~/Downloads/Silhouette.jpg failed

The contents of the markdown file are:
```Markdown
![This is an image](~/Downloads/Silhouette.jpg)
```

I get the same WARN with other markdown files that reference an image - be it jpg or png.

iTerm2 3.4.22
inlyne 0.4.2
MacOs 14.4.1

**Comment by CosmicHorrorDev** [comment] 2024-04-15 16:01
The issue is that it doesn't resolve `~` as your home (usually shells expand that and some programs mimic that behavior). Generally you'll use relative paths for things like that, so that it works for other people too, but an absolute path should also work

**Comment by patrick-men** [comment] 2024-04-16 08:44
That worked, thank you!

**Comment by CosmicHorrorDev** [comment] 2024-04-16 19:50
Happy to hear :D

I'll go ahead and close this then

**Closed by CosmicHorrorDev** 2024-04-16 19:50 UTC
